# Generated by Django 6.0.8 on 2026-09-23 23:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'غير مطلوب'), ('awaiting', 'بانتظار الدفع'), ('verifying', 'قيد التحقق'), ('paid', 'مدفوع'), ('refunded', 'مسترد')], default='not_required', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='kind',
            field=models.CharField(choices=[('created', 'إنشاء الطلب'), ('status_changed', 'تغيير الحالة'), ('assigned', 'إسناد'), ('note_added', 'ملاحظة'), ('attachment_added', 'مرفق'), ('quote_created', 'عرض سعر'), ('quote_decided', 'قرار عرض السعر'), ('payment_status', 'حالة الدفع'), ('payment_recorded', 'تسجيل دفعة')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('SDG', 'جنيه سوداني'), ('USD', 'دولار أمريكي'), ('SAR', 'ريال سعودي')], max_length=3)),
                ('method', models.CharField(choices=[('cash', 'نقدًا'), ('bank_transfer', 'تحويل بنكي'), ('mobile_money', 'تطبيق دفع'), ('other', 'أخرى')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(choices=[('SDG', 'جنيه سوداني'), ('USD', 'دولار أمريكي'), ('SAR', 'ريال سعودي')], max_length=3)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'بانتظار موافقة العميل'), ('accepted', 'وافق العميل'), ('rejected', 'رفض العميل'), ('superseded', 'استُبدل بعرض أحدث')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='orders.order')),
            ],
            options={
                'ordering': ['version'],
                'constraints': [models.UniqueConstraint(fields=('order', 'version'), name='unique_quote_version')],
            },
        ),
    ]
