# Generated by Django 6.0.8 on 2026-09-24 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9_.-]{2,29}$', 'من 3 إلى 30 حرفًا: أحرف إنجليزية صغيرة وأرقام و _ . -، ويبدأ بحرف أو رقم.')], verbose_name='اسم المستخدم'),
        ),
    ]
