# Generated by Django 6.0.8 on 2026-09-23 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('subject', models.CharField(max_length=140)),
                ('body', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المتابعة'), ('done', 'تمت المعالجة')], db_index=True, default='new', max_length=12)),
                ('internal_note', models.TextField(blank=True, max_length=4000)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
