# Generated by Django 6.0.8 on 2026-09-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=2000)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='بريد عرجون', max_length=80)),
                ('tagline', models.CharField(default='نقرّب لك المسافات', max_length=120)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp_text', models.CharField(default='مرحبًا، أود الاستفسار عن خدمات بريد عرجون.', max_length=300)),
                ('show_whatsapp', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('hero_eyebrow', models.CharField(default='من السودان، أقرب إليك', max_length=120)),
                ('hero_title', models.CharField(default='خدمات متنوعة.\nومسافات أقرب.', max_length=160)),
                ('hero_text', models.TextField(default='كل ما تحتاجه لإنجاز خطوتك القادمة، في مكان واحد.\nاختر خدمتك، أرسل طلبك، ودع التفاصيل علينا.', max_length=600)),
                ('about', models.TextField(default='منصة تجمع خدمات متنوعة في تجربة بسيطة، وتضع وضوح الخطوات في المقدمة.', max_length=2000)),
                ('seo_title', models.CharField(default='بريد عرجون | خدمات تقرّب المسافات', max_length=70)),
                ('seo_description', models.CharField(default='خدمات متنوعة، وطلب تتابعه بسهولة.', max_length=170)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
