# Generated by Django 6.0.8 on 2026-09-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_seed_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_file_mb',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='حجم الملف الأقصى MB'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_files_per_order',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='عدد الملفات لكل طلب'),
        ),
    ]
