# Generated by Django 6.0.8 on 2026-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sitesettings_max_file_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notify_emails',
            field=models.CharField(blank=True, help_text='عناوين مفصولة بفاصلة', max_length=500, verbose_name='بريد التنبيهات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_messages',
            field=models.BooleanField(default=True, verbose_name='تنبيه عند رسالة جديدة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_orders',
            field=models.BooleanField(default=True, verbose_name='تنبيه عند طلب جديد'),
        ),
    ]
