# Generated by Django 6.0.8 on 2026-09-25 14:53

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_sitesettings_hero_image_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_sections',
            field=models.JSONField(default=apps.content.models.default_home_sections),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navigation',
            field=models.JSONField(default=apps.content.models.default_navigation),
        ),
    ]
