# Generated by Django 6.0.8 on 2026-09-23 22:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='الاسم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=140, unique=True)),
                ('description', models.TextField(max_length=4000, verbose_name='الوصف')),
                ('tagline', models.CharField(blank=True, max_length=120, verbose_name='عبارة البطاقة')),
                ('requirements', models.TextField(blank=True, max_length=4000, verbose_name='المتطلبات')),
                ('duration_text', models.CharField(blank=True, max_length=120, verbose_name='المدة التقديرية')),
                ('price_type', models.CharField(choices=[('after_review', 'بعد مراجعة الطلب'), ('fixed', 'سعر ثابت'), ('starting_from', 'يبدأ من')], default='after_review', max_length=20)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_currency', models.CharField(blank=True, default='SDG', max_length=3)),
                ('icon_key', models.CharField(default='package', max_length=20)),
                ('color', models.CharField(default='sage', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('hidden', 'مخفية')], db_index=True, default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=True, verbose_name='تظهر في الرئيسية')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('form_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('help_text', models.CharField(blank=True, max_length=240)),
                ('type', models.CharField(choices=[('text', 'نص قصير'), ('textarea', 'نص طويل'), ('number', 'رقم'), ('date', 'تاريخ'), ('select', 'اختيار واحد'), ('multiselect', 'اختيارات متعددة'), ('address', 'عنوان')], default='text', max_length=12)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('max_length', models.PositiveIntegerField(default=1000)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(allow_unicode=True, max_length=140, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_redirects', to='catalog.service')),
            ],
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price_type', 'after_review'), ('price_amount__isnull', False), _connector='OR'), name='service_price_amount_required'),
        ),
        migrations.AddConstraint(
            model_name='servicefield',
            constraint=models.UniqueConstraint(fields=('service', 'key'), name='unique_field_key_per_service'),
        ),
    ]
