# Generated by Django 6.0.8 on 2026-09-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefield',
            name='max_files',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicefield',
            name='type',
            field=models.CharField(choices=[('text', 'نص قصير'), ('textarea', 'نص طويل'), ('number', 'رقم'), ('date', 'تاريخ'), ('select', 'اختيار واحد'), ('multiselect', 'اختيارات متعددة'), ('address', 'عنوان'), ('file', 'ملف'), ('image', 'صورة')], default='text', max_length=12),
        ),
    ]
