# Generated by Django 6.0.8 on 2026-09-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_servicefield_max_files_alter_servicefield_type'),
        ('media_library', '0002_publicasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='media_library.publicasset'),
        ),
    ]
