# Generated by Django 6.0.8 on 2026-09-30 19:17

import django.db.models.deletion
from collections import Counter

from django.db import migrations, models


def icons_from_services(apps, schema_editor):
    """Existing categories take the icon most of their services use."""
    Category = apps.get_model("catalog", "Category")
    for category in Category.objects.all():
        keys = Counter(category.services.values_list("icon_key", flat=True))
        if keys:
            category.icon_key = keys.most_common(1)[0][0]
            category.save(update_fields=["icon_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_image'),
        ('media_library', '0002_publicasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=160, verbose_name='سطر تعريفي'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_key',
            field=models.CharField(default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='media_library.publicasset'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='يظهر في الرئيسية'),
        ),
        migrations.RunPython(icons_from_services, migrations.RunPython.noop),
    ]
