# Generated by Django 6.0.8 on 2026-09-30 20:32

from collections import Counter

from django.db import migrations, models


def split_texts(apps, schema_editor):
    """The one-line «سطر تعريفي» becomes the short description; the long one
    starts empty. Each area takes the colour most of its services use."""
    Category = apps.get_model("catalog", "Category")
    for c in Category.objects.all():
        if c.description and not c.tagline:
            c.tagline, c.description = c.description[:120], ""
        colours = Counter(c.services.values_list("color", flat=True))
        if colours:
            c.color = colours.most_common(1)[0][0]
        c.save(update_fields=["tagline", "description", "color"])


def join_texts(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    for c in Category.objects.all():
        if c.tagline and not c.description:
            c.description = c.tagline[:160]
            c.save(update_fields=["description"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='sage', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.CharField(blank=True, max_length=120, verbose_name='الوصف المصغّر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='الوصف المطوّل'),
        ),
        migrations.RunPython(split_texts, join_texts),
    ]
