# Generated by Django 6.0.8 on 2026-09-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='html_body',
            field=models.TextField(blank=True),
        ),
    ]
